# Generated by Django 4.2.2 on 2023-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_position_placeimage_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ('position',), 'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, default=1, null=True),
        ),
    ]
