#!/usr/bin/env bash
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Арт-пространство%20«Бункер%20703».json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Водопад%20Радужный.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Воробьёвы%20горы.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Генератор%20Маркса%20или%20«Катушка%20Тесла».json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Горбовская%20ГЭС.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Дизайн-квартал%20Флакон.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Дом%2C%20где%20снимался%20фильм%20«Покровские%20ворота».json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Заброшенный%20пионерский%20лагерь%20«Белое%20озеро».json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Заброшенный%20пионерский%20лагерь%20«Сказка».json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Источник%20Преподобного%20Сергия%20Радонежского.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Коворкинг%20Gravity.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Креативное%20пространство%20«Люмьер-Холл».json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Лагерь%20«Подмосковный».json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Лопатинский%20рудник.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Места%2C%20где%20снимался%20%20фильм%20«Операция%20„Ы“%20и%C2%A0другие%20приключения%20Шурика».json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Многофункциональный%20технологичный%20лофт%20TelePort360°.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Музей%20автомобильных%20историй.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Останкинская%20телебашня.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Павильон%20«Космос»%20на%20ВДНХ.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Пещеры%20Сьяны.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Площадка%20для%20свиданий%20на%2060-м%20этаже%20Москва-Сити.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Смотровая%20площадка%20PANORAMA360%20в%C2%A0ММДЦ%20«Москва-Сити».json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Смотровая%20площадка%20«Выше%20Только%20Любовь».json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Эйфелева%20башня%20в%20Москве.json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Экскурсионная%20компания%20«Легенды%20Москвы».json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Экскурсионный%20проект%20«Крыши24.рф».json
python3 ./manage.py load_place https://raw.githubusercontent.com/devmanorg/where-to-go-places/master/places/Японский%20сад.json